version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE='${DB_DATABASE:-laravel}'
      - DB_USERNAME='${DB_USERNAME:-user}'
      - DB_PASSWORD='${DB_PASSWORD:-secret}'
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: laravel_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-secret}'
      MYSQL_DATABASE: '${DB_DATABASE:-laravel}'
      MYSQL_USER: '${DB_USERNAME:-user}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
